import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { test } from 'node:test';
import { stagedFixtureFilename } from '../../tests/AXI-1604/harness/synthetic-grados-seed';

/**
 * UT-GRADOS-1700-1..3 (epic AXI-1687 - FR57, SI-044). A re-stage is a NEW dataset version:
 * the upload name is content-addressed, so regenerated bytes never reuse (or overwrite) the
 * dataset the demo narratives already point at. Pure, offline, no Anthropic call.
 */

const CSV = path.join(process.cwd(), 'tests', 'AXI-1604', 'fixtures', 'synthetic-grados-cohort.csv');

test('UT-GRADOS-1700-1: the staged filename carries a 12-hex content digest and keeps the .csv suffix', () => {
  assert.match(stagedFixtureFilename(readFileSync(CSV)), /^synthetic-grados-cohort-[0-9a-f]{12}\.csv$/);
});

test('UT-GRADOS-1700-2: identical bytes stage under the same name (idempotent re-run)', () => {
  const bytes = readFileSync(CSV);
  assert.equal(stagedFixtureFilename(bytes), stagedFixtureFilename(new Uint8Array(bytes)));
});

test('UT-GRADOS-1700-3: changed bytes stage under a NEW name (a new dataset, never the old one served stale)', () => {
  const bytes = readFileSync(CSV);
  const changed = Buffer.concat([bytes, Buffer.from('SUBJ-999,1\n')]);
  assert.notEqual(stagedFixtureFilename(bytes), stagedFixtureFilename(changed));
});
